version: '3.2'

services:

  nginx:
    build: ./docker/nginx
    container_name: 'pricing-nginx'
    privileged: true
    working_dir: /app
    ports:
      - '8182:80'
      - '8183:443'
    networks:
      - default
      - pricing-network
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certificate.crt:/etc/nginx/conf.d/certificate.crt
      - ./docker/nginx/certificate.key:/etc/nginx/conf.d/certificate.key
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: 'pricing-php'
    privileged: true
    working_dir: /app
    ports:
      - '9000:9000'
    networks:
      - default
      - pricing-network
    volumes:
      - ./:/app
      - ./docker/php/config:/usr/local/etc/php
      - ./docker/php/logs/php:/var/log/php

networks:
  pricing-network:
    driver: bridge
